version: '3.8'

services:
  wordpress:
    image: 363174885355.dkr.ecr.eu-north-1.amazonaws.com/wordpress-app:31
    container_name: wordpress
    volumes:
      - ./config/wordpress.sites-available.default:/etc/nginx/conf.d/default.conf
      - ./config/wordpress-nginx.conf:/etc/nginx/nginx.conf
      - ./config/wp-config.php:/var/www/html/wp-config.php
      - ./config/www.conf:/etc/php/8.1/fpm/pool.d/www.conf
      - ./src/wordpress/wp-content/:/var/www/html/wp-content/
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
    networks: 
      - private_net
    depends_on:
      - db
    restart: always

  proxy:
    image: nginx:stable
    container_name: proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./config/proxy.sites-available.default:/etc/nginx/conf.d/default.conf
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - ./certs/letsencrypt:/etc/letsencrypt
    logging:
      driver: awslogs
      options:
        awslogs-group: nginx-proxy-access-logs
        awslogs-stream: nginx-access-logs-stream
    networks:
      - public_net
      - private_net
    restart: always
    
  db:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - private_net
    restart: always


networks:
  public_net:
  private_net:
    external: true

volumes: 
  db_data:
    
    

    