name: Deploy Wordpress App Dev
on:
  workflow_run:
    workflows: ["Build Wordpress Container Dev"]
    types:
      - completed
jobs:
  change_image_tag:
    runs-on: self-hosted
    permissions:
      actions: read
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: image_tag
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}
      - name: Extract Image Tag from Artifact
        run: echo "IMAGE_TAG=$(cat image_tag.txt)" >> $GITHUB_ENV
      - name: Get Code from Deployment Repository
        uses: actions/checkout@v4
        with: 
          repository: 'konbusalov/wordpress-app-deployment'
          path: 'deployment_repo'
          token: ${{ secrets.BOT_TOKEN }}
          persist-credentials: true
      - name: Edit docker-compose
        run: |
          echo "The Image Tag is: $IMAGE_TAG"
          cd deployment_repo
          sed -i -E "s#(image: ${{secrets.AWS_ACCOUNT_ID}}.dkr.ecr.${{vars.AWS_DEFAULT_REGION}}.amazonaws.com/wordpress-app:dev-)[0-9]+#\1$IMAGE_TAG#" docker-compose-dev.yml
          git add docker-compose-dev.yml
          git status --porcelain | wc -l
          if [[ $(git status --porcelain | wc -l) -gt 0 ]]; then
            git config --global user.name "Deployment [bot]"
            git config --global user.email "${{vars.EMAIL}}"
            git commit -m "Updated docker-compose-dev.yml image tag to $IMAGE_TAG"
            git push
          else 
            echo "No changes to commit"
          fi

  deploy:
    runs-on: self-hosted
    needs: change_image_tag
    steps:
      - name: Write SSH Private Key To File 
        run: |
          mkdir -p ~/.ssh
          echo "${{secrets.SSH_PRIVATE_KEY}}" > ~/.ssh/private_key.pem
          chmod 600 ~/.ssh/private_key.pem
      - name: Add Server into known_hosts
        run: |
          ssh-keyscan ${{secrets.DEPLOYMENT_SERVER_IP}} >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts
      - name: SSH and Deploy on Server
        run: |
          ssh -i ~/.ssh/private_key.pem ubuntu@${{secrets.DEPLOYMENT_SERVER_IP}} << 'EOF'
            cd wordpress-app-deployment
            git pull origin master --no-rebase
            ./start.sh
          EOF

