name: First Workflow
on: push
jobs:
  first-job:
    runs-on: self-hosted
    steps:
      - name: Print greeting
        run: echo "Hello World!"
      - name: Print goodbye
        run: echo "Done - Bye!"